### ISSUE TITLE
Copying from clipboard not working

### ISSUE THREAD

**Issue by ghost** [padlock/padlock#138]
I exported encrypted data from Padlock v2.1.1 iOS, transferred to Android 7.1 Padlock v2.2.0. But the import from clipboard does not do anything. It did not transfer the contents. I checked if the data is present in clipboard by pasting it in a text editor. It has full content.

I then had to use padlock cloud sync to transfer the data, which worked.

Sidenote: the new UI/UX improvements are really cool.

**Comment by MaKleSoft** [comment]
@kadaj We've had similar reports before but so far haven't been able to reproduce the problem. How did you transfer the data from your iOS device to your Android device?

**Comment by kadaj** [comment]
I transferred via email as text without zipping.

**Comment by MaKleSoft** [comment]
Fixed in v3, as copying from clipboard will be replaced in favor of file import.
