### ISSUE TITLE
UX: Titlebar doesn't match my UI Environment

### ISSUE THREAD

**Issue by Nols1000** [padlock/padlock#158]
Hi,

the Titlebar does not match the style of my UI Environment (KDE). Would it be possible to don't style it and leave it the window manager to decide how the Titlebar should be styled. I find it inconvenient that the close button is on the left side instead of the right side and the buttons are smaller than I'm used to.

**Comment by MaKleSoft** [comment]
@Nols1000 Hm, I hear what you're saying. I was only testing this with the standard Ubuntu UI and didn't really consider other UI Environments. I think the right course of action is to simply use the system UI for the titlebar on Linux.
