### ISSUE TITLE
maximum call stack size exceeded

### ISSUE THREAD

**Issue by combinatorist** [padlock/padlock#184]
I got this error while using the v2.7.1 and trying to add a field to a record.

Environment:
- **app version:** 2.7.1
- **device:** iPhone 5
- **OS:** IOS 10.3.3

**Comment by MaKleSoft** [comment]
How did the error present itself? Did the app show a popup or something? Is the error reproducible?

**Comment by MaKleSoft** [comment]
Finally managed to reproduce this. Fix coming soon.

**Comment by combinatorist** [comment]
Sorry, @MaKleSoft! I was on vacation and didn't see your email until just now. Thanks for fixing this and for making an all-around great product!
