### ISSUE TITLE
Supporting U2F

### ISSUE THREAD

**Issue by pwasiewicz** [padlock/padlock#186]
As it was statement before, TouchID or general fingerprint-based authentication won't be supported. But what about U2F protocol? Yubikey (and not only) grow stronger and 2nd authentication factor could be easier to use than few years go. 

I think I do not need to mention, how 2FA is important, especially to place, where all of my passwords are stored.

**Comment by MaKleSoft** [comment]
As I explain in https://github.com/padlock/padlock/issues/24, I'm not convinced that hardware or software-based two-factor authentication offers any significant security improvement for Padlock.

Biometric authentication is an entirely different story and while I've been very skeptical about it in the past, I think that the technology has matured enough to be feasible either as a additional authentication layer or, in combination with a secure system-level enclave, as an alternative for entering the password every time.

In short, the encryption scheme at the core of Padlock should be robust enough to be secure without any additional shenanigans. Stacking more layers on top of it will only make the architecture more complex and prone to vulnerabilities through faulty implementation. "Security through simplicity" is an essential part of our philosophy and while some users may *feel* more secure with 2fa support, I fail to see how it would be of any meaningful value to Padlock.

**Comment by DimanNe** [comment]
@MaKleSoft Is it a joke?

What about the fact that U2F token protect its users from fishing sites (before giving user credentials token verifies site)? This feature alone is a significant security improvement, is not it?

**Comment by MaKleSoft** [comment]
@DimanNe This is a very old ticket. We're actually working on U2F/FIDO support as we speak. Stay tuned! 😉
