### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by suihkulokki** [padlock/padlock#187]
Since the appimage is only available on x86_64, I took the adventure of building the app for my arm64 machine. This lead to some errors

- npm install fails first with "pusd: not found"

On Debian/Ubuntu, /bin/sh is not bash, and thus scripts are executed a more bare shell. Fixed in package.json with:
```
-    "bower-install": "pushd app && bower install && popd",
+    "bower-install": "cd app && bower install && cd ..",

``` 
Next error:
```
> gulp compile --silent

events.js:167
      throw er; // Unhandled 'error' event
      ^
TypeScript error: test/data.ts(43,13): Error TS2345: Argument of type '"my category"' is not assignable to parameter of type 'string[] | undefined'.
```
Unfortunately I have no idea how to proceed with that. Nodejs reports v10.3.0 and npm 6.1.0

"npn run app" will however work a this point, apart from an ugly traceback due to lack of https://github.com/maklesoft/padlock/releases/download/v2.7.1/latest-linux-arm64.yml

**Comment by MaKleSoft** [comment]
Thanks for reporting this! I'm afraid our test cases have been falling behind a little bit which is the reason for the compilation error. You can just ignore those errors for now as they shouldn't have any impact on running the app.
