### ISSUE TITLE
download links not working

### ISSUE THREAD

**Issue by brianmorton** [padlock/padlock#188]
specifically https://github.com/padlock/padlock/releases/download/v2.7.2/Padlock-2.7.2.dmg which is on the current release page.

```
$ wget https://github.com/padlock/padlock/releases/download/v2.7.2/Padlock-2.7.2.dmg
--2018-06-13 09:35:41--  https://github.com/padlock/padlock/releases/download/v2.7.2/Padlock-2.7.2.dmg
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-06-13 09:35:41 ERROR 404: Not Found.
```

**Comment by MaKleSoft** [comment]
Wow, that was quick 😅! I had pulled the release for a minute to add the windows build. Should work again now.

**Comment by brianmorton** [comment]
@MaKleSoft thanks - I'm a homebrew-cask contrib just making sure your cask stays updated ;)

**Comment by MaKleSoft** [comment]
There is a homebrew cask? 😳

**Comment by brianmorton** [comment]
There is indeed :)

**Comment by MaKleSoft** [comment]
That's awesome! Thanks for maintaining it!
