### ISSUE TITLE
Where does padlock appimage store passwords

### ISSUE THREAD

**Issue by osemenovsky** [padlock/padlock#189]
While reinstalling the system, i forgot to export passwords from padlock, i have a backup of my home directory, but i can't find location that padlock uses as a storage, could you point me to that?

**Comment by osemenovsky** [comment]
Is there any way at all to retrieve the passwords from previous installation of padlock, considering that i know the master password?
I've been able to do this once before with the chrome-app version of padlock, but i don't know how to do the same thing with the appimage

**Comment by MaKleSoft** [comment]
It should be under `~/.config/Padlock/data.pls`. Btw, you can view and adjust the database path from the settings screen:

<img width="567" alt="screen shot 2018-06-19 at 09 48 31" src="https://user-images.githubusercontent.com/1270940/41583921-3228cf72-73a6-11e8-95ad-59012beef503.png">

**Comment by osemenovsky** [comment]
Thank you a lot!
