### ISSUE TITLE
Padlock is using a consistent amout of  CPU (5%) when idle under Linux

### ISSUE THREAD

**Issue by moritzheiber** [padlock/padlock#193]
When Padlock is running, unlocked, under Linux, it appears to be using a consistent 5% of my CPU resources. I'm not sure what it's doing the whole time, but it sure shouldn't be doing anything that requires it to use 5% of my system's resources the whole time?

Let me know if there's anything I can help with in terms of tracking this down.

OS: Xubuntu Linux 18.04
Version: 2.7.2, custom server with auto-sync enabled

**Comment by MaKleSoft** [comment]
@moritzheiber Hm, that's interesting. Can you run run a performance profile for me? You can do that from the "performance" tab in dev tools while running in debug mode: `npm run app -- --debug`.  You can find instructions on how to run the app from source in the [readme](https://github.com/padlock/padlock#getting-started).

**Comment by moritzheiber** [comment]
I would love to, but there are two things that are keeping from doing that:

1. npm/yarn scripts don't like `pushd` and `popd` (probably because they use `/bin/sh` internally, although my settings clearly say `/bin/bash`):

```
$ yarn install
yarn install v1.7.0
info No lockfile found.
[1/4] Resolving packages...
warning bower@1.8.4: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
warning electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0: 
warning gulp > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning gulp > vinyl-fs > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-stream > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
warning gulp-insert-lines > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ npm run bower-install && npm run compile && mkdir -p cordova/www

> padlock@2.7.2 bower-install /home/moe/Code/padlock
> pushd app && bower install && popd

sh: 1: pushd: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! padlock@2.7.2 bower-install: `pushd app && bower install && popd`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the padlock@2.7.2 bower-install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/moe/.npm/_logs/2018-07-09T13_35_55_355Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
Once I just remove the `pushd/popd` instructions and replace it with
```javascript
"bower-install": "cd app && bower install"
```
(it's an isolated shell after all) I'm running into the following issue:
```
Unable to find a suitable version for webcomponentsjs, please choose one by typing one of the numbers below:
    1) webcomponentsjs#1.0.13 which resolved to 1.0.13 and is required by padlock
    2) webcomponentsjs#^v1.0.2 which resolved to 1.0.13 and is required by polymer#2.1.1
    3) webcomponentsjs#^v1.1.0 which resolved to 1.2.2 and is required by polymer#2.6.0

Prefix the choice with ! to persist it to bower.json

? Answer
```
No matter the choice this process then ends up here:
```
> padlock@2.7.2 compile /home/moe/Code/padlock
> gulp compile --silent


events.js:183
      throw er; // Unhandled 'error' event
      ^
TypeScript error: test/data.ts(43,13): Error TS2345: Argument of type '"my category"' is not assignable to parameter of type 'string[] | undefined'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! padlock@2.7.2 compile: `gulp compile --silent`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the padlock@2.7.2 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/moe/.npm/_logs/2018-07-09T13_39_16_585Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Let me know whether I need to do anything else.

**Comment by MaKleSoft** [comment]
@moritzheiber The last error you are seeing is due to some outdated tests (see https://github.com/padlock/padlock/issues/187) and can be ignored for now. Have you tried running the app despite the errors?

**Comment by moritzheiber** [comment]
I did, where can I dump the profile? It's 8.5MB compressed (and it shows the CPU profile clearly spiking at the end)

**Comment by MaKleSoft** [comment]
@moritzheiber You can send it to support@padlock.io. You can attach it directly or share it via Dropbox or WeTransfer or something.

**Comment by moritzheiber** [comment]
I sent the email.

**Comment by MaKleSoft** [comment]
Amazing, thanks! This actually looks quite different from what I'm seeing on MacOS. I'll take a closer look at it when I have the time. If anyone is seeing something similar I'd love to get more data.

**Comment by moritzheiber** [comment]
The steps I took were essentially:

1. Start app
2. Create new, offline database
3. Choose master password
4. Enable syncing with my self-hosted instance
5. Send login token
6. Confirm login via token
7. Sync local store with online server

The CPU usage jumped between 125 and 130 seconds and stayed on a constant level throughout.

**Comment by MaKleSoft** [comment]
> The CPU usage jumped between 125 and 130 seconds

Do you remember if you did anything specific in that time frame? If you restart the app, does the CPU usage go straight back up to the elevated level?

**Comment by moritzheiber** [comment]
I did not do anything specific, in fact, I think the app was entering an idle cycle during that time because I switched away from it.

I'll try to collect a profile after restarting the app.

**Comment by moritzheiber** [comment]
I could not get a coherent profile which was replicating the behavior 1-1, but it's consistent in the rise of CPU after a short while.

**Comment by Canule** [comment]
No heavy load(kernel 4.15.0-29) 0%,
Just a massive 130MB RAM!

**Comment by moritzheiber** [comment]
Okay, I'm unable to reproduce this again, for now. Closing/will re-open if it pops up again :+1:

**Comment by MaKleSoft** [comment]
@moritzheiber thanks for the follow-up!
