### ISSUE TITLE
Update check makes the AppImage hang

### ISSUE THREAD

**Issue by bjoern-tantau** [padlock/padlock#196]
Github seems to be throwing a 500 Internal Server Error at the moment, which crashes the update check. Unfortunately the Appimage doesn't do anything else after that. It doesn't close and more importantly it doesn't show its window.

The first few lines of output on the terminal are

> Checking for update
> xdg-mime: application argument missing
> Try 'xdg-mime --help' for more information.
> Error: Error: Cannot parse releases feed: Error: Unable to find latest version on GitHub (https://github.com/maklesoft/padlock/releases/latest), please ensure a production release exists: HttpError: 500 Internal Server Error

I'll attach the rest of the output.

[padlock-dump.log](https://github.com/padlock/padlock/files/2198854/padlock-dump.log)

**Comment by bjoern-tantau** [comment]
This is on Kubuntu 18.04.

**Comment by bjoern-tantau** [comment]
Actually, I just set autoDownloadUpdates to false in the settings.json. I didn't get any exceptions anymore, but it wouldn't start anyway. 
That's when I noticed that height was set to 1 in settings.json. So it just looked like it wasn't starting properly. No idea if the two issues are related. Setting height back to 600 at least made the app appear again. :-)

Sometimes my windows resize when I turn off or switch monitors. But then I can see at least the title bar.

**Comment by MaKleSoft** [comment]
> Github seems to be throwing a 500 Internal Server Error at the moment, which crashes the update check.

Hm, I wonder if this was a temporary problem or if it has something to do with the fact that we recently moved the repo to from "maklesoft/padlock" to "padlock/padlock". Maybe the update checker had problems following the redirect. In any case, this shouldn't result in the app crashing, of course. So we'll have to make sure the error is handled correctly if it occurs.

> That's when I noticed that height was set to 1 in settings.json. So it just looked like it wasn't starting properly. No idea if the two issues are related. Setting height back to 600 at least made the app appear again. :-)

The app automatically stores the window dimensions every time the window is resized. If your window manager messes with your window sizes, that's not really the fault of the app 😜 It would make sense to enforce a minimum window height and width. That would be a separate issue though.
