### ISSUE TITLE
Honeypot records

### ISSUE THREAD

**Issue by combinatorist** [padlock/padlock#197]
Honeypots or canary tokens are a great way to find out if someone is illicitly accessing your data.

I wonder how hard it would be to create a honeypot feature in padlock where as soon as a user clicks on or expands a particular record, it alerts a user-specified email address?

## Workarounds:
- The user could create an empty, harmless email or financial account that alerts them when someone logs in. Then, they could store the credentials in padlock as a honeypot. But, that would only work if the attacker actually attempted log-in of the honeypot account.
- I suppose the honeypot is mostly redundant assuming the user does not store their master password anywhere else and they monitor the devices accessing their account.
  - However, in case an attacker did slip past those safeguards, the honeypot would still expose the fact the attacker's ignorance since the true user would never click on the honeypot.

But, mostly I'm just getting really paranoid for the fun of it. :)

**Comment by MaKleSoft** [comment]
That's an interesting idea. The problem, of course, is that this requires the attacker to actually use the app interface to access the records. If an attacker knows your master password *and* has access to your phone, they're more likely to export the data directly. In any case, it is unlikely that an attacker would ever use the app at all, but rather target the data at rest, running a brute-force attack on the database directly without ever loading the interface.

I agree that it's fun to think to think about sneaky ways to "catch the bad guys", but with the exception of a few special cases, this rarely works. Better to rely on protection methods that don't make assumptions about the attackers specific behaviour and focus on the most likely / efficient attack vectors. In this case this means making sure that the data is properly protected at rest, which comes down to using a strong master password and **keeping it secret**.

Thanks for the suggestion though. I tend to bat down most security-related feature requests but that doesn't mean I don't appreciate the effort. So please do keep them coming 😉

**Comment by combinatorist** [comment]
Agreed, @MaKleSoft - thanks for humoring me!
