### ISSUE TITLE
iOS custom server not syncing

### ISSUE THREAD

**Issue by Eliottiosdevs** [padlock/padlock#198]
Hi, 

First of all awesome project!

Today I installed Padlock on my iPhone and when trying to connect to my custom server, I go to login and get Failed connection error.

Any idea

Thanks,
Eliott

**Comment by tomonacci** [comment]
@Eliottiosdevs I sync from my iPhone 6s to my custom server and it works just fine... have you checked the usual pitfalls like firewall settings on your server?

**Comment by Eliottiosdevs** [comment]
Hi @tomonacci 

First of all thanks for replying,

I'm up to date, and got it working on my macbook and Ubuntu device. Only problem is iOS

**Comment by MaKleSoft** [comment]
@Eliottiosdevs Are you using the [--cors flag](https://github.com/padlock/padlock-cloud#chrome-app-fails-to-connect-to-custom-server)?

**Comment by Eliottiosdevs** [comment]
No @MaKleSoft should I?

**Comment by Eliottiosdevs** [comment]
That did it

**Comment by Eliottiosdevs** [comment]
Thank you very much! Really appreciated! Awesome project btw @MaKleSoft congrats!
