### ISSUE TITLE
Desktop version

### ISSUE THREAD

**Issue by Canule** [padlock/padlock#199]
Are there any intentions to drop the included UI for a desktop version?
It is clearly a phone app.

-Very low information density(lists) (big font/spacing Playmobil interface).
-Slow scrolling through list(Linux U18.04)
-No OS theming.
-Useless sluggish crashing animations(win10 1803). 
![crashania](https://user-images.githubusercontent.com/16336062/45220465-7b732f00-b2ae-11e8-982d-67a0ae7ea6b7.png)
![crashanib](https://user-images.githubusercontent.com/16336062/45220411-4ff04480-b2ae-11e8-9417-4aa267ef8978.png)
-Very high memory usage both Windows/Linux(+130MB).
-No auto focus on input field  pw/ua.
-No way to disable annoying reminders about stuff I m not gonna use.
-No hot keys ESC/Backspace/... to go a layer back from object input fields, but there is ESC assigned for the search field, or exit settings, but not the tag screen(in-consequent).

Great core, terrible UI for the desktop, sorry I just hate its poor flow for the desktop environment  :)

**Comment by Canule** [comment]
https://github.com/padlock/padlock/issues/161

**Comment by MaKleSoft** [comment]
@Canule Thanks for your feedback. We're currently revising the UI as part of the 3.0 release and we'll keep your comments in mind.
