### ISSUE TITLE
Stateless Password Generation

### ISSUE THREAD

**Issue by jonwrede** [padlock/padlock#203]
I got interested in stateless password generation like [LessPass](https://lesspass.com/) or [MasterPassword](https://masterpassword.app/) but I don't think being totally stateless is an option. Because there is usually related information in need of being protected. I was wondering if there is already a plan for a generation option like that. I would greatly appreciate any comments and thoughts on the issue.

**Comment by MaKleSoft** [comment]
Stateless password managers are an interesting concept but imho have too many problems in practice to be a viable alternative to "classic" password managers in most real world applications. I don't really see how the concept of "statelessness" would fit into the current design or improve it in any way. Can you elaborate on what kind of features you are envisioning specifically?

**Comment by jonwrede** [comment]
I guess i should elaborate further. Im not talking about replacing the "classic" password managers. Since there is always data that can't be generated. That's why i hesitate to move my password to a "stateless" password manager. I envision an integration with padlock. I would be greate to be able to chose the generation algorithm as "stateless" and have the corresponding metadata saved in side padlock. I have not looked deeper into the code. But i expect die implementation to be quite straight forward. Since all changes would take place in the UI. The data that needs to be stored is:
`{
    "login": "38491092",
    "site": "www.ingdirect.fr",
    "lowercase": false,
    "uppercase": false,
    "symbols": false,
    "numbers": true,
    "counter": 1,
    "length": 6
}` for LessPass. The improvment would be that if you dont have access to your vault you would still beable to figure out our password. If i want to get this functionality, with a regular password manager i need to remember the password. Which makes the password manger obsolete for the accounts i want to login without access to my vault. But with a "stateless" password manger these problems would vanish. Hope that clears some of the confusion.

**Comment by MaKleSoft** [comment]
> The improvment would be that if you dont have access to your vault you would still beable to figure out our password.

How is that? Even for a stateless password manager you'll still need a "seed" of some kind which needs to be store somewhere. With Padlock you can already access your data offline once it's downloaded. How is your scenario different?
