### ISSUE TITLE
Upgrade to enable synchronization!

### ISSUE THREAD

**Issue by jimvonmoon** [padlock/padlock#207]
![padlock](https://user-images.githubusercontent.com/2614851/51073977-cfd15580-1678-11e9-8572-f66958266fe5.png)
What does this mean? I am running my own padlock-cloud server in local network.

Client version (Windows and Android): 2.7.2
Server version (running on Raspbian): 1.2.0

**Comment by MaKleSoft** [comment]
Are you sure you're connected to your own server? This should only show up if you're connected to cloud.padlock.io and don't have an active subscription. Did you set the "custom server" option?

**Comment by jimvonmoon** [comment]
Yes, I am sure I was connecting to my local server all the time. The weird thing is that the message disappeared after client reset. I guess everything is ok now. Thanks!
