### ISSUE TITLE
Blockchain authentication using Digi-ID

### ISSUE THREAD

**Issue by tristanmarvin** [padlock/padlock#212]
Using Digi-ID to authenticate.  Digi-ID is an open-source, community-driven Open Auth project based on the DigiByte Blockchain. It will always remain free.  Accounts details, Secure Notes, Restore phases, all? All that lost for a forgotten password or a hacked account? Not anymore. With Digi-ID, blockchain-based tech protects all accounts. 
https://youtu.be/pLrQycud5GI
https://www.digi-id.io/

**Comment by MaKleSoft** [comment]
Not sure what you're pitching here, but this sounds more like a buzzword-driven marketing stunt than anything else. Closing this until I hear an actual feature request or question.
