### ISSUE TITLE
Could Not Contact Server

### ISSUE THREAD

**Issue by combinatorist** [padlock/padlock#217]
For several days at least, I've been getting a Could Not Contact Server error (in an orange box) immediately after logging in on both a Macbook Pro and a linux laptop. This is concerning because my iPhone 5 suddenly stopped accepting my master password (same one I've used to successfully login on the laptops). So, it appears no two of my devices have been able to sync for at least a week.

**Comment by MaKleSoft** [comment]
Hi there! We are not experiencing any server outages right now so it seems this problem may be related to your account specifically (Unless you're running your own server?). Please shoot us an email at support@padlock.io with your accounts email address and I'll look into it!
