### ISSUE TITLE
Passwords Vanishing

### ISSUE THREAD

**Issue by c00w** [padlock/padlock#218]
I've had multiple issues of my passwords vanishing from padlock. Can we please have a was to access deleted items so this can be fixed easily?

**Comment by MaKleSoft** [comment]
Can you provide a little more information about this problem? I.e. did you recognize any pattern with the "vanishing" of the passwords? Is there a certain series of steps to reproduce the problem?

**Comment by c00w** [comment]
I honestly didn't recognize anything distinctive here. It was present one night then gone the next. If there is a way to pull debug logs I'm happy to do it. (Alternatively I'd love a way to disable deletions).

**Comment by MaKleSoft** [comment]
Hm, without a way to reproducing the problem there is not much we can do about it. Closing this issue for now. Let me know if the problem persists!
